PetShop/PetShop/Models/Animal.cs
namespace PetShop.Models;

public class Animal
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int Age { get; set; }
    public string TypeAnimal { get; set; }
    public string Breed { get; set; }
    public int Price { get; set; }
    public string Description { get; set; }
    public string Image { get; set; }
}

PetShop/PetShop/Models/AnimalsContext.cs
namespace PetShop.Models;

public class AnimalsContext
{
    
}

PetShop/PetShop/Models/ErrorViewModel.cs
namespace PetShop.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

PetShop/PetShop/Models/PetStoreContext.cs
using Microsoft.EntityFrameworkCore;

namespace PetShop.Models;

public class PetStoreContext : DbContext
{
    public DbSet<Animal> Animals { get; set; }
    public PetStoreContext(DbContextOptions<PetStoreContext> options) : base(options) {}
}

PetShop/PetShop/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc;
using PetShop.Models;

namespace PetShop.Controllers;

public class AnimalController : Controller
{
    private readonly PetStoreContext _context;

    public AnimalController(PetStoreContext context)
    {
        _context = context;
    }
    
    public IActionResult Index()
    {
        List<Animal> animals = _context.Animals.ToList();
        return View(animals);
    }
    
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Create(Animal? animal)
    {
        if (animal != null)
        {
            _context.Add(animal);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        return View(animal);
    }

    public IActionResult Details(int animalId)
    {
        Animal animal = _context.Animals.FirstOrDefault(a => a.Id == animalId);
        if (animal != null)
        {
            return View(animal);
        }

        return NotFound();
    }

    public IActionResult Delete(int animalId)
    {
        Animal animal = _context.Animals.FirstOrDefault(a => a.Id == animalId);
        {
            if (animal != null)
            {
                _context.Remove(animal);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

PetShop/PetShop/Views/Animal/Create.cshtml
@model Animal

@{
    Layout = "_Layout";
}

<div class="row">
    <div class="bg-dark text-center pt-5 pb-4">
        <h3 class="text-white mb-5">Fill out the form to add a new pet</h3>
        <form asp-action="Create" method="post">
            <div class="form_row mb-3">
                <label for="" class="col-4">
                    <input type="text" class="form-control" asp-for="Name" placeholder="Enter pet name...">
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="" class="col-4">
                    <input type="number" class="form-control" asp-for="Age" placeholder="Indicate age pet...">
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="" class="col-4">
                    <input type="text" class="form-control" asp-for="TypeAnimal" placeholder="Specify type pet...">
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="" class="col-4">
                    <input type="text" class="form-control" asp-for="Breed" placeholder="Specify breed pet...">
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="" class="col-4">
                    <input type="text" class="form-control" asp-for="Image" placeholder="Provide a link to the pet image...">
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="" class="col-4">
                    <textarea asp-for="Description" type="text" class="form-control" placeholder="Tell us about pet..." rows="3"></textarea>
                </label>
            </div>
            <div class="form_row mb-3">
                <label for="" class="col-4">
                    <input type="number" class="form-control" asp-for="Price" placeholder="Specify the cost...">
                </label>
            </div>
            <button type="submit" class="btn btn-outline-light mb-3 w-25">Add new pet</button>
        </form>
    </div>
</div>

PetShop/PetShop/Views/Animal/Details.cshtml
@model Animal

@{
    ViewBag.Title = "Detailed view of the pet";
}


<div class="bg-dark text-white pt-4 mt-5">
    <div class="row px-5">
        <div class="col-4 border-end border-white">
            <h4 class="text-center mb-5">Info</h4>
            <p><strong>Id: </strong>@Model.Id</p>
            <p><strong>Type animal: </strong>@Model.TypeAnimal</p>
            <p><strong>Breed: </strong>@Model.Breed</p>
            <p><strong>Age: </strong>@Model.Age</p>
            <p><strong>Price: </strong>@Model.Price</p>
            <p class="text-center mt-3"><a asp-action="Index" asp-controller="Animal" class="btn btn-outline-light w-50">Back</a></p>
        </div>
        <div class="col-8 text-center">
            <img href="@Model.Image" alt="Photo of a pet">
        </div>
        <div class="border-top border-white">
            <h4 class="text-center mt-3">About pet</h4>
            <p>@Model.Description</p>
        </div>
    </div>
</div>

PetShop/PetShop/Views/Animal/Index.cshtml
@model List<Animal>

@{
    ViewBag.Title = "Animals list";
}

@if (Model != null && Model.Count != 0)
{
    <table class="table table-striped">
        <thead class="table-dark">
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>TypeAnimal</th>
            <th>Breed</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var a in Model)
        {
            <tr>
                <td>@a.Name</td>
                <td>@a.Age</td>
                <td>@a.TypeAnimal</td>
                <td>@a.Breed</td>
                <td>@a.Price</td>
                <td>
                    <a asp-action="Details" asp-controller="Animal" asp-route-animalId="@a.Id" class="btn btn-outline-dark">Details</a>
                    <a asp-action="Delete" asp-controller="Animal" asp-route-animalId="@a.Id" class="btn btn-outline-danger">Delete</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <h4 class="text-center">Unfortunately, at the moment, pets have not added yet :с</h4>
}

PetShop/PetShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PetShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/PetShop.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand text-white" asp-area="" asp-controller="Animal" asp-action="Index">Pets list</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Animal" asp-action="Create">Add new pet</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>